# Generated by Django 5.1.1 on 2024-09-21 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_date_joined_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 20, 59, 49, 26344, tzinfo=datetime.timezone.utc)),
        ),
    ]
