# Generated by Django 5.1.1 on 2024-09-21 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 21, 2, 18, 449054, tzinfo=datetime.timezone.utc)),
        ),
    ]
