# Generated by Django 5.1.1 on 2024-09-21 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_name_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 21, 21, 7, 11, 347559, tzinfo=datetime.timezone.utc)),
        ),
    ]
